#!/bin/sh -e

patch -p1 < patches/fix-clang.patch

sed -i 's/inc apps/inc/' Makefile

export LDFLAGS="-z norelro"

gmake \
    CC=clang \
    ARCH=x86_64

gmake \
    CC=clang \
    ARCH=x86_64 \
    -C lib

gmake \
    CC=clang \
    ARCH=x86_64 \
    -C gnuefi

gmake \
    CC=clang \
    ARCH=x86_64 \
    -C inc

gmake INSTALLROOT="$1" PREFIX='/usr' install

install -vDm 644 README.efilib -t "$1/usr/share/licenses/gnu-efi"
install -vDm 644 ChangeLog README.gnuefi README.git README.elilo -t "$1/usr/share/doc/gnu-efi"
