#!/bin/sh -e

export NOTO_PATH=$1/usr/share/fonts/noto/

mkdir -p $NOTO_PATH

cp ./fonts/NotoColorEmoji.ttf $NOTO_PATH
chmod 644 $NOTO_PATH/NotoColorEmoji.ttf

cp ./fonts/NotoEmoji-Regular.ttf $NOTO_PATH
chmod 644 $NOTO_PATH/NotoEmoji-Regular.ttf
