#!/bin/sh -e

for patch in *.patch; do
    patch -p1 < "$patch"
done

./autogen.sh
./configure --prefix=/usr

make install

mkdir -p "$1/usr/share/man/man8/"

cp gummiboot.8 "$1/usr/share/man/man8/gummiboot.8"
