#!/bin/sh -e

mkdir -p bld/release && cd bld/release

meson --prefix=/usr --buildtype=release --buildtype=release -Denable-cairo=disabled -Denable-png=enabled -Denable-svg=disabled . output

ninja -C output install
