#!/bin/sh -e

for patch in *.patch; do
    patch -p1 < "$patch"
done

cmake . \
		-DCMAKE_BUILD_TYPE=None \
		-DCMAKE_INSTALL_PREFIX=/usr \
		-DCMAKE_INSTALL_LIBDIR=lib \
		-DBUILD_SHARED_LIBS=ON \
		-DGLFW_USE_WAYLAND=ON

make
make DESTDIR="$1/" install
